site_name: Crawl Program 문서
site_description: 크롤링 프로그램 내부 개발 문서

docs_dir: docs
site_dir: site

theme:
  name: material
  language: ko

  features:
    - navigation.indexes
    - navigation.top
    - content.code.copy

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/sidebar-resizer.js

nav:
  - crawl-program:
      - index.md
      - main.py: main.md

      - src:
          - repositories:
              - worker_db_repository.py: src/repositories/worker_db_repository.md

          - workers:
              - api_naver_place_loc_all_set_worker:
                  - api_naver_place_loc_all_set_worker.md: src/workers/main/api_naver_place_loc_all_set_worker/api_naver_shop_total_detail_set_worker.md
                  - HISTORY.md: src/workers/main/api_naver_place_loc_all_set_worker/HISTORY.md
                  - README.md: src/workers/main/api_naver_place_loc_all_set_worker/README.md

              - api_yeogi_admin_set_worker:
                  - api_yeogi_admin_set_worker.md: src/workers/main/api_yeogi_admin_set_worker/api_naver_shop_total_detail_set_worker.md
                  - HISTORY.md: src/workers/main/api_yeogi_admin_set_worker/HISTORY.md
                  - README.md: src/workers/main/api_yeogi_admin_set_worker/README.md

              - api_zigzag_set_worker:
                  - api_zigzag_set_worker.md: src/workers/main/api_zigzag_set_worker/api_naver_shop_total_detail_set_worker.md
                  - HISTORY.md: src/workers/main/api_zigzag_set_worker/HISTORY.md

              - api_base_worker.py: src/workers/api_base_worker.md